### ISSUE TITLE
Update to new nomenclature in Canto  -> @kimrutherford

### ISSUE THREAD

**Issue by manulera** [pombase/allele_qc#79]

**Comment by kimrutherford** [comment]
Hi @manulera

What do I need to do for this issue?

**Comment by manulera** [comment]
Hi @kimrutherford. Sorry for the empty issue. This is to update descriptions once I have a file migrating from the current nomenclature to the new one, so similar to #76, but with more alleles

**Comment by manulera** [comment]
Hi @kimrutherford, there is a new set of changes in this file that contain the migration to the new syntax:

https://github.com/pombase/allele_qc/blob/master/manual_fixes_pombase/allele_auto_fix_old2new.tsv

And a few minor manual fixes:

https://github.com/pombase/allele_qc/blob/master/manual_fixes_pombase/unknowns_with_correct_descriptions.tsv

If you can integrate those, we are done with migration to the new syntax.

**Comment by kimrutherford** [comment]
Hi Manu.  I tried applying both file on my desktop copy on the Canto database.  It all looks good.  I'll apply the fixes to the main pombe Canto tonight (UK/Spanish time).

**Comment by manulera** [comment]
🥳🥳🥳

**Comment by kimrutherford** [comment]
>  I'll apply the fixes to the main pombe Canto tonight (UK/Spanish time).

That's done in time for the nightly load.

**Comment by manulera** [comment]
Hi Kim,

It seems that the changes did not go through, but actually it's ok because I have realised one type of change was not recorded. I will fix it and let you know.

**Comment by manulera** [comment]
@kimrutherford, I have added a few extra rows (below) to this table with missing fixes.

https://github.com/pombase/allele_qc/blob/3a05faa9e437a15b222f197d0ff9d36ef1dbb47f/manual_fixes_pombase/unknowns_with_correct_descriptions.tsv#L7-L12

Basically, the auto-fix was not going in (rightly so) because the alleles had sequence errors. I have added some CTD fixes as well.

**Comment by kimrutherford** [comment]
> For example:
> systematic_id	allele_description	allele_name	allele_type	change_description_to
> SPAC23C11.16	FN-519-AA	plo1-FN519AA	amino_acid_mutation	FN519AA	
> Did not go through

Hi Manu.  I'm a bit confused.  Which allele fixes file has the changes that didn't go through?

**Comment by kimrutherford** [comment]
>  I'm a bit confused. Which allele fixes file has the changes that didn't go through?

Sorry, ignore me.  :-)

I'm not confused anymore and I've applied the allele fixes to the PHAF files.

**Comment by kimrutherford** [comment]
The load failed because of an unrelated reason (the PubMed API had a temporary error) so we'll need to wait until Thursday to check the alleles in Chado.

**Comment by manulera** [comment]
Alright, thanks!

**Comment by kimrutherford** [comment]
> we'll need to wait until Thursday to check the alleles in Chado.

The load works and it looks like the alleles are fixed.  Let me know if you see any problems.

**Comment by manulera** [comment]
Hi @kimrutherford, it seems that most of them went through, but there are a few that did not. It seems that they are the ones that either had an empty description, or an empty name. Because they are only in one publication each, I will just go ahead and fix them manually.

```
systematic_id 	allele_description 	allele_name      	allele_type                       	change_description_to 	change_name_to 	change_type_to              	auto_fix_comment                                                                                                         	sequence_error 	solution_index 	allele_parts 	rules_applied                           	reference     	comment_on_change 	add_synonym 	add_comment
SPAC140.02    	                   	gar2::ura4+      	disruption                        	gar2::ura4            	               	                            	syntax_error                                                                                                             	               	               	gar2::ura4+  	disruption:usual                        	PMID:9211982  	                  	            	
SPAC1565.08   	G338D              	                 	amino_acid_mutation               	G332D                 	               	                            	old_coords_fix, revision 8148: join(1306439..1306512,1306569..1308942)                                                   	G338           	               	G338D        	amino_acid_mutation:single_aa           	PMID:29352077 	                  	            	
SPAC57A10.14  	Q64->stop          	                 	nonsense_mutation                 	Q64*                  	               	partial_amino_acid_deletion 	syntax_and_type_error                                                                                                    	               	               	Q64->stop    	nonsense_mutation:stop_codon_text       	PMID:29352077 	                  	            	
SPBC16D10.04c 	K961T              	                 	amino_acid_mutation               	K960T                 	               	                            	old_coords_fix, revision 20110324: complement(join(3592359..3592685,3592733..3593447,3593496..3596292,3596335..3596692)) 	K961           	               	K961T        	amino_acid_mutation:single_aa           	PMID:22682245 	                  	            	
SPBC3H7.13    	                   	csc1::ura4+      	disruption                        	csc1::ura4            	               	                            	syntax_error                                                                                                             	               	               	csc1::ura4+  	disruption:usual                        	PMID:23874188 	                  	            	
SPCC306.03c   	T117I              	                 	amino_acid_insertion_and_mutation 	                      	               	amino_acid_mutation         	type_error                                                                                                               	               	               	T117I        	amino_acid_mutation:single_aa           	PMID:31072933 	                  	            	
SPCC338.08    	60-100             	ctp1-delta60-100 	amino_acid_mutation               	                      	               	partial_amino_acid_deletion 	type_error                                                                                                               	               	               	60-100       	partial_amino_acid_deletion:multiple_aa 	PMID:25580577 	                  	            	
SPCC622.09    	G52D               	                 	amino_acid_mutation               	G53D                  	               	                            	histone_fix                                                                                                              	G52            	               	G52D         	amino_acid_mutation:single_aa           	PMID:29352077 	                  	            	

```

**Comment by manulera** [comment]
Then, this one: `ctp1-delta60-100` is from the phaf files. I don't know why it was not fixed. Maybe in the phaf file script you are not taking into account the `change_type_to` column?

**Comment by manulera** [comment]
> Then, this one: ctp1-delta60-100 is from the phaf files. I don't know why it was not fixed

I fixed this one manually as well, in svn revision 9086. I think the reason why it did not go through might be because in the file it says `amino acid mutation` instead of `amino_acid_mutation` in the type.

**Comment by manulera** [comment]
Hi @kimrutherford

Just a summary of the previous comments:I fixed everything on my side, but the ones listed

```diff
Index: trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1315954_phaf.tsv
===================================================================
--- trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1315954_phaf.tsv	(revision 9086)
+++ trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1315954_phaf.tsv	(working copy)
@@ -2,8 +2,8 @@
 #Submitter_ORCID: 0000-0003-4148-4606
 #Submitter_status: PomBase
 Gene systematic ID	FYPO ID	Allele description	Expression	Parental strain	Strain background	Genotype	Gene name	Allele name	Allele synonym	Allele type	Evidence	Condition	Penetrance	Severity	Extension	Reference	taxon	Date	ploidy
-SPNCRNA.98	FYPO:0002060	U88G, nt84-88 deletion, 131 nucleotides inserted after nt83	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega131nt		other	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
-SPNCRNA.98	FYPO:0002061	U88G, nt84-88 deletion, 131 nucleotides inserted after nt83	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega131nt		other	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
+SPNCRNA.98	FYPO:0002060	U88G,84-88,131 nucleotides inserted after nt83	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega131nt		other	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
+SPNCRNA.98	FYPO:0002061	U88G,84-88,131 nucleotides inserted after nt83	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega131nt		other	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G72A,G78A,G100A,G107A,G112A,G141A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G72A,G78A,G100A,G107A,G112A,G141A	srp7-G72A,G78A,G100A,G107A,Gl12A,G141A	nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002061	G72A,G78A,G100A,G107A,G112A,G141A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G72A,G78A,G100A,G107A,G112A,G141A	srp7-G72A,G78A,G100A,G107A,Gl12A,G141A	nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002061	G153A,G155A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G153A,G155A		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
@@ -13,7 +13,7 @@
 SPNCRNA.98	FYPO:0002061	139-144	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7delta139-144		partial nucleotide deletion	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002061	118-120	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7delta118-120		partial nucleotide deletion	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002061	A146T,G159T,148-150	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-A146U,G159U,delta148-150		nucleotide_deletion_and_mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
-SPNCRNA.98	FYPO:0002061	U88G, nt84 deletion, 8 nucleotides inserted after nt83	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega8nt		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
+SPNCRNA.98	FYPO:0002061	T84GCTGCAGC,T88G	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,delta84-88,omega8nt		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G4C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G4C		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G100A,C103A,G112A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G100A,C103A,G112A		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	C69T	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-C69U		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
@@ -60,7 +60,7 @@
 SPNCRNA.98	FYPO:0002060	T88G,T133C,A135C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,U133C,A135C		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	T101C,A136C,G149C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U101C,A136C,G149C		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	T(-61)C,G(-75)C,T62C,T101C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-T(-61)C,G(-75)C,U62C,U101C		nucleotide mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
-SPNCRNA.98	FYPO:0002060	U88G, UCGA inserted after nt84	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,omegaUCGA		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
+SPNCRNA.98	FYPO:0002060	T88G,T84TTCGA	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,omegaUCGA		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000005,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G4C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G4C		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G100A,C103A,G112A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G100A,C103A,G112A		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	C69T	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-C69U		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
@@ -107,7 +107,7 @@
 SPNCRNA.98	FYPO:0002060	T88G,T133C,A135C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,U133C,A135C		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	T101C,A136C,G149C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U101C,A136C,G149C		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	T(-61)C,G(-75)C,T62C,T101C	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-T(-61)C,G(-75)C,U62C,U101C		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
-SPNCRNA.98	FYPO:0002060	U88G, UCGA inserted after nt84	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,omegaUCGA		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
+SPNCRNA.98	FYPO:0002060	T88G,T84TTCGA	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-U88G,omegaUCGA		nucleotide_insertion_and_mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G4A,G9A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G4A,G9A		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G4A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G4A		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
 SPNCRNA.98	FYPO:0002060	G9A	Not specified	972 h-		ura4-D18 leu1-32 ade6-704		srp7-G9A		nucleotide mutation	Cell growth assay	FYECO:0000004,FYECO:0000137				PMID:1315954	4896	2014-06-09	
Index: trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1332977_phaf.tsv
===================================================================
--- trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1332977_phaf.tsv	(revision 9086)
+++ trunk/external_data/phaf_files/chado_load/ltp_phafs/PMID_1332977_phaf.tsv	(working copy)
@@ -34,12 +34,12 @@
 SPBC1A4.03c	FYPO:0004056	43-75,1221-1485	not assayed	972 h-			top2	top2delta(42-74)-delta-Xba		partial_amino_acid_deletion	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002061	1-54,1221-1485	not assayed	972 h-			top2	top2delta(1-53)-delta-Xba		partial_amino_acid_deletion	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002779	1-54,1221-1485	not assayed	972 h-			top2	top2delta(1-53)-delta-Xba		partial_amino_acid_deletion	microscopy	FYECO:0000005,FYECO:0000126			assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002060	amino acids 26-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-26-40/SV-delta-Xba		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0000838	amino acids 26-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-26-40/SV-delta-Xba		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126			assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002060	amino acids 1-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-1-40/SV-delta-Xba		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0004056	amino acids 1-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-1-40/SV-delta-Xba		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000003	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002061	amino acids 1-74 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-1-74/SV-delta-Xba		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0004056	amino acids 1-74 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1221-1485 deleted	not assayed	972 h-			top2	top2-1-74/SV-delta-Xba		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002060	27-41,T26TPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-26-40/SV-delta-Xba		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0000838	27-41,T26TPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-26-40/SV-delta-Xba		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126			assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002060	2-41,M1MPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-1-40/SV-delta-Xba		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0004056	2-41,M1MPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-1-40/SV-delta-Xba		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000003	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002061	2-75,M1MPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-1-74/SV-delta-Xba		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0004056	2-75,M1MPKKKRKV,1221-1485	not assayed	972 h-			top2	top2-1-74/SV-delta-Xba		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002061	1-75,1200-1485	not assayed	972 h-			top2	top2delta(1-74)-delta-Sph		partial_amino_acid_deletion	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002779	1-75,1200-1485	not assayed	972 h-			top2	top2delta(1-74)-delta-Sph		partial_amino_acid_deletion	microscopy	FYECO:0000005,FYECO:0000126			assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002060	1-18,1200-1485	not assayed	972 h-			top2	top2delta(1-17)-delta-Sph		partial_amino_acid_deletion	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
@@ -50,9 +50,9 @@
 SPBC1A4.03c	FYPO:0004056	43-75,1200-1485	not assayed	972 h-			top2	top2delta(42-74)-delta-Sph		partial_amino_acid_deletion	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002061	1-54,1200-1485	not assayed	972 h-			top2	top2delta(1-53)-delta-Sph		partial_amino_acid_deletion	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
 SPBC1A4.03c	FYPO:0002779	1-54,1200-1485	not assayed	972 h-			top2	top2delta(1-53)-delta-Sph		partial_amino_acid_deletion	microscopy	FYECO:0000005,FYECO:0000126			assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002060	amino acids 26-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-26-40/SV-delta-Sph		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0004056	amino acids 26-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-26-40/SV-delta-Sph		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002060	amino acids 1-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-1-40/SV-delta-Sph		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0004056	amino acids 1-40 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-1-40/SV-delta-Sph		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0002061	amino acids 1-74 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-1-74/SV-delta-Sph		amino acid mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
-SPBC1A4.03c	FYPO:0004056	amino acids 1-74 replaced by SV40 NLS sequence PKKKRKV, and amino acids 1200-1485 deleted	not assayed	972 h-			top2	top2-1-74/SV-delta-Sph		amino acid mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000001	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002060	27-41,T26TPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-26-40/SV-delta-Sph		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0004056	27-41,T26TPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-26-40/SV-delta-Sph		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002060	2-41,M1MPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-1-40/SV-delta-Sph		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0004056	2-41,M1MPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-1-40/SV-delta-Sph		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000002	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0002061	2-75,M1MPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-1-74/SV-delta-Sph		amino_acid_insertion_and_mutation	cell growth assay	FYECO:0000005				PMID:1332977	4896	2016-07-05	
+SPBC1A4.03c	FYPO:0004056	2-75,M1MPKKKRKV,1200-1485	not assayed	972 h-			top2	top2-1-74/SV-delta-Sph		amino_acid_insertion_and_mutation	microscopy	FYECO:0000005,FYECO:0000126		FYPO_EXT:0000001	assayed_using(PomBase:top2)	PMID:1332977	4896	2016-07-05	

```

**Comment by manulera** [comment]
I think we can close with this!
